# Generated by Django 2.2.9 on 2020-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0003_auto_20200213_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='addres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
