# Generated by Django 2.2.9 on 2020-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind', '0004_auto_20200214_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='gmaddres',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='addres',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
